name: Check For Protected File Changes

on:
  pull_request_target:

permissions: write-all

jobs:
  check-if-protected-files-are-modified:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Check for file changes using git-protect
        run: python .github/scripts/git_protect.py ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} > output.txt

      - name: Post a comment back to the PR if protected files have changed
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v2
        with:
            file_path: output.txt

        

